### ISSUE TITLE
To Do List week of December 4th

### ISSUE THREAD

**Issue by bubblesort251** [mickovski/lendingclub#4]
### Task 0: Take the tasks in this issue and make a separate issue for each of them.  
* Subtask 1: Assign each issue to yourselves.  Note, this week's work is very serial (i.e hard to work on this independently).  **ONCE YOU FINISH A SUBTASK, PUSH THE CODE TO GITHUB.  OTHERWISE NO ONE ELSE CAN PICK UP WHERE YOU LEFT OFF**

### Task 1: Figure out Lending Club API
* Subtask 1: Identify a way to pull historical loan data and performance
   *  i.e pull loans available on Jan 1st 2015, the information available at the time (e.g FICO score, number of delinquencies on file, ...) and performance data (e.g number of good payments made)
* Subtask 2: Find / Build documentation for the lending club variables
   *  i.e Build an excel document, in each row has a variable name, and a description or a link to a description

### Task 2: Target Variable Creation:
* Subtask: Build a function that takes a lending club loan's performance data and builds a target variable
    * Inputs: Performance data, #of months currently delinquent 
    * Output: Binary 1,0
    *  Function: If the performance data says that the loan is >= #of months currently delinquent or has defaulted then 1 else 0

### Task 3: Use Lasso Regression to identify variables to use in model
* Subtask 1: Find link to Lasso regression, post in issue for this subtask (and read what LASSO is)
* Subtask 2: Run Lasso regression with a penalty, and see what variables are non zero
* Subtask 3: **If you have time do this step** Use cross validation to pick the best penalization value_

**Comment by mickovski** [comment]
[LASSO.pdf](https://github.com/mickovski/lendingclub/files/1545048/LASSO.pdf)
